name: NSE Institutional Tracker

on:
  workflow_dispatch:   # allows manual run

  schedule:
    - cron: "30 13 * * *"   # 7:00 PM IST (GitHub uses UTC)

jobs:
  run-bot:

    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NSE tracker
        run: |
          echo "Starting NSE tracker..."
          python main.py
